### ISSUE TITLE
Unknown or missing action parameter

### ISSUE THREAD

**Issue by steveliedtke** [claytondaley/yourls-api-list#1]
Hi,

I just tried using your plugin with my yourls installation and after activating and trying to use the functionality, it responds 

{
"errorCode": 400,
"message": "Unknown or missing \"action\" parameter"
}

Other action parameters work.

Did this plugin worked before? Can you reproduce this behaviour?

Thanks in advance

**Comment by claytondaley** [comment]
I don't have an active install to test.  Did you enabled the plugin?

**Comment by steveliedtke** [comment]
Yes, I enabled the plugin via the 'tools' section in the yourls admin ui

**Comment by steveliedtke** [comment]
Found the problem, see Pull request

**Comment by claytondaley** [comment]
Thanks!  Must have fixed it locally and never gotten around to pushing it.
